do not retry resource templating on error for "onetime" resources
HeavyHorst/remco pull request #79
Opened 2022-02-14 13:00 UTC by sseide

this patch exits after one failed attempt when a resource has the "Onetime" flag set.
The resource is not retried for connection errors (no route to host or wrong password) and templating errors (template file missing, wrong key referenced,...)

As i do not speak this language i do not know if this is the way to "go" to return error values for the process on execution failures. From a users point of view it is really helpful to have an exit code != 0 on failures but this seems a bit more complicated with go and defered and channels and stuff...

Open for any changes here...

remark: the `make test` is failing with an yaml pongo2 error. This test fails without this PR too.

2022-02-16 10:53 UTC, sseide commented
Remark about the tests failed (i am using Linux):

On local execution neither `gradlew check`, `gradlew verifyReleaseDependencies`, `gradlew :src:dist:verifyReleaseDependencies` nor `gradlew createDist` fail with a mismatch in `src/dist/src/dist/expected_release_jars.csv`.
And runing any of these tasks with the `-PupdateExpectedJars` does not update the csv file too.

But the checks running on Windows and MacOS do fail because the `expected_release_jars.csv` file is not up-to-date.
* https://github.com/apache/jmeter/runs/5214556695?check_suite_focus=true
* https://github.com/apache/jmeter/runs/5214556790?check_suite_focus=true

How should i update the file on Linux? Manually? Some windows/Linux gradle wrapper not in sync?

2022-02-17 19:33 UTC, HeavyHorst requested changes
Thanks!

Looks good to me. We just have to add the mutex/atomic synchronisation.

2022-02-17 19:33 UTC, HeavyHorst commented on cmd/remco/supervisor.go
> +				ru.resourcesWithError++
I think we need to protect the variable with a mutex or use atomic operations (https://pkg.go.dev/sync/atomic) as we use multiple parallel goroutines here.

2022-02-17 19:33 UTC, HeavyHorst commented on cmd/remco/supervisor.go
> +						ru.resourcesWithError++
Mutex or atomic synchronisation.

2022-02-18 09:58 UTC, sseide commented
thanks - added atomic increment and read. Had to change counter type, but hope noone will try to template more than max signed int32 config resources in parallel...

2022-02-19 17:47 UTC, merged